// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/build4/Dashboard.tsx": () => import("../components/mockups/build4/Dashboard.tsx"),
  "./components/mockups/build4/Refreshed.tsx": () => import("../components/mockups/build4/Refreshed.tsx")
};
